task :load_rubric_fields => [:environment] do
  a = Assignment.find_by_name('Waiting in Line')
  a.rubric_fields.create(:name=>'Interview')
  a.rubric_fields.create(:name=>'Ideate and Iterate')
  a.rubric_fields.create(:name=>'Prototype')
  a.rubric_fields.create(:name=>'Reflection')
  a.rubric_fields.create(:name=>'Video Questions')
  a.rubric_fields.create(:name=>'Lab Prep')

  a = Assignment.find_by_name('Needfinding')
  a.rubric_fields.create(:name=>'Observation Quantity')
  a.rubric_fields.create(:name=>'Observation: Breakdowns & Opportunities')
  a.rubric_fields.create(:name=>'Photos/Sketches')
  a.rubric_fields.create(:name=>'Ideation Quantity')
  a.rubric_fields.create(:name=>'Ideation Quality')
  a.rubric_fields.create(:name=>'Needfinding Talk')

  a = Assignment.find_by_name('Prototyping')
  a.rubric_fields.create(:name=>'Point of View')
  a.rubric_fields.create(:name=>'Inspiration Quality')
  a.rubric_fields.create(:name=>'Storyboard #1')
  a.rubric_fields.create(:name=>'Storyboard #2')
  a.rubric_fields.create(:name=>'Prototype #1')
  a.rubric_fields.create(:name=>'Prototype #2')

  a = Assignment.find_by_name('Heuristic evaluation')
  a.rubric_fields.create(:name=>'Relation to Nielsen’s Heuristics')
  a.rubric_fields.create(:name=>'Volume of Feedback')
  a.rubric_fields.create(:name=>'Quality of Feedback')
  a.rubric_fields.create(:name=>'Severity Ratings')
  a.rubric_fields.create(:name=>'Aggregate Evaluation & Reflection')
  a.rubric_fields.create(:name=>'Home Screen')

  a = Assignment.find_by_name('Skeleton and a plan')
  a.rubric_fields.create(:name=>'List of Changes')
  a.rubric_fields.create(:name=>'Development Plan')
  a.rubric_fields.create(:name=>'Home Screen & Key Screens')
  a.rubric_fields.create(:name=>'Navigational Skeleton')
  a.rubric_fields.create(:name=>'Revisit the Brief')

  a = Assignment.find_by_name('Meat on the bones')
  a.rubric_fields.create(:name=>'Interaction Flow')
  a.rubric_fields.create(:name=>'Reading data w/JSON & Handlebars')
  a.rubric_fields.create(:name=>'Goals Met')
  a.rubric_fields.create(:name=>'Development Plan: Quality & Updates')
  a.rubric_fields.create(:name=>'Supporting Info')

  a = Assignment.find_by_name('Ready for testing')
  a.rubric_fields.create(:name=>'Functionality')
  a.rubric_fields.create(:name=>'Data/Templates')
  a.rubric_fields.create(:name=>'Mobile Design')
  a.rubric_fields.create(:name=>'Goals')
  a.rubric_fields.create(:name=>'Updated Development Plan')
  a.rubric_fields.create(:name=>'Task Description')

  a = Assignment.find_by_name('Test your prototype')
  a.rubric_fields.create(:name=>'Experimental Protocol & Documentation')
  a.rubric_fields.create(:name=>'Photo Documentation')
  a.rubric_fields.create(:name=>'Planned Changes')
  a.rubric_fields.create(:name=>'Alternative Design')
  a.rubric_fields.create(:name=>'Online Test Plan')
  a.rubric_fields.create(:name=>'Updated Development Plan')

  a = Assignment.find_by_name('Results!')
  a.rubric_fields.create(:name=>'Online Test Results')
  a.rubric_fields.create(:name=>'List of Potential Revisions')
  a.rubric_fields.create(:name=>'Fit and Finish')
  a.rubric_fields.create(:name=>'Goals')
  a.rubric_fields.create(:name=>'Updated Development Plan')

  a = Assignment.find_by_name("Final Presentation")
  a.rubric_fields.create(:name=>'Pitch')
  a.rubric_fields.create(:name=>'Poster')
  a.rubric_fields.create(:name=>'Demo')
  a.rubric_fields.create(:name=>'Visual Design')
  a.rubric_fields.create(:name=>'User Need')
  a.rubric_fields.create(:name=>'Point of View')
end